### ISSUE TITLE
Desarrollo de contendio

### ISSUE THREAD

**Issue by ambarja** [gavg712/taller-r-scripts-for-qgis#1]
@gavg712 por el momento yo me encargo de ver el **desarrollo de la instalación y configuración** para los 3 sistemas operativos, asimismo me encargo de desarrollar el contenido **introductorio a QGIS y R**.
Para las capturas de pantallas esto usando GIMP.

**Comment by gavg712** [comment]
@ambarja Estoy trabajando en el primer ejercicio y la explicación de como escribir la ayuda
